// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio;

namespace Repositorio.Migrations
{
    [DbContext(typeof(AplicacaoContexto))]
    [Migration("20210317222838_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelos.Arcano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int>("TipoArcano");

                    b.HasKey("Id");

                    b.ToTable("Arcanos");
                });

            modelBuilder.Entity("Modelos.Atributo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Atributos");
                });

            modelBuilder.Entity("Modelos.Efeito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int>("TipoEfeito");

                    b.HasKey("Id");

                    b.ToTable("Efeitos");
                });

            modelBuilder.Entity("Modelos.EfeitoCaracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EfeitoId");

                    b.Property<int>("TipoCaracteristica");

                    b.HasKey("Id");

                    b.HasIndex("EfeitoId");

                    b.ToTable("EfeitoCaracteristicas");
                });

            modelBuilder.Entity("Modelos.Formacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Formacoes");
                });

            modelBuilder.Entity("Modelos.Nacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Nacoes");
                });

            modelBuilder.Entity("Modelos.Pericia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Pericias");
                });

            modelBuilder.Entity("Modelos.Personagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bio");

                    b.Property<int>("Ferimentos");

                    b.Property<int>("FerimentosDramaticos");

                    b.Property<int>("Fortuna");

                    b.Property<Guid>("NacaoId");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<Guid>("ReligiaoId");

                    b.HasKey("Id");

                    b.HasIndex("NacaoId");

                    b.HasIndex("ReligiaoId");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("Modelos.PersonagemArcano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ArcanoId");

                    b.Property<Guid>("PersonagemId");

                    b.HasKey("Id");

                    b.HasIndex("ArcanoId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemArcanos");
                });

            modelBuilder.Entity("Modelos.PersonagemAtributo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AtributoId");

                    b.Property<Guid>("PersonagemId");

                    b.Property<int>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemAtributos");
                });

            modelBuilder.Entity("Modelos.PersonagemEfeito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<Guid>("EfeitoId");

                    b.Property<Guid>("PersonagemId");

                    b.Property<int>("TempoAtividade");

                    b.Property<int>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("EfeitoId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemEfeitos");
                });

            modelBuilder.Entity("Modelos.PersonagemFormacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("FormacaoId");

                    b.Property<Guid>("PersonagemId");

                    b.HasKey("Id");

                    b.HasIndex("FormacaoId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemFormacoes");
                });

            modelBuilder.Entity("Modelos.PersonagemPericia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("PericiaId");

                    b.Property<Guid>("PersonagemId");

                    b.Property<int>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("PericiaId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemPericias");
                });

            modelBuilder.Entity("Modelos.PersonagemVantagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("PersonagemId");

                    b.Property<int>("Valor");

                    b.Property<Guid>("VantagemId");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId");

                    b.HasIndex("VantagemId");

                    b.ToTable("PersonagemVantagens");
                });

            modelBuilder.Entity("Modelos.Religiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Religioes");
                });

            modelBuilder.Entity("Modelos.Vantagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Vantagens");
                });

            modelBuilder.Entity("Modelos.EfeitoCaracteristica", b =>
                {
                    b.HasOne("Modelos.Efeito", "Efeito")
                        .WithMany("CaracteristicasAfetadas")
                        .HasForeignKey("EfeitoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modelos.Personagem", b =>
                {
                    b.HasOne("Modelos.Nacao", "Nacao")
                        .WithMany("Habitantes")
                        .HasForeignKey("NacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Modelos.Religiao", "Religiao")
                        .WithMany("Fieis")
                        .HasForeignKey("ReligiaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modelos.PersonagemArcano", b =>
                {
                    b.HasOne("Modelos.Arcano", "Arcano")
                        .WithMany()
                        .HasForeignKey("ArcanoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Modelos.Personagem", "Personagem")
                        .WithMany()
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modelos.PersonagemAtributo", b =>
                {
                    b.HasOne("Modelos.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Modelos.Personagem", "Personagem")
                        .WithMany("Atributos")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modelos.PersonagemEfeito", b =>
                {
                    b.HasOne("Modelos.Efeito", "Efeito")
                        .WithMany()
                        .HasForeignKey("EfeitoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Modelos.Personagem", "Personagem")
                        .WithMany("Efeitos")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modelos.PersonagemFormacao", b =>
                {
                    b.HasOne("Modelos.Formacao", "Formacao")
                        .WithMany()
                        .HasForeignKey("FormacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Modelos.Personagem", "Personagem")
                        .WithMany("Formacoes")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modelos.PersonagemPericia", b =>
                {
                    b.HasOne("Modelos.Pericia", "Pericia")
                        .WithMany()
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Modelos.Personagem", "Personagem")
                        .WithMany("Periciais")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modelos.PersonagemVantagem", b =>
                {
                    b.HasOne("Modelos.Personagem", "Personagem")
                        .WithMany("Vantagens")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Modelos.Vantagem", "vantagem")
                        .WithMany()
                        .HasForeignKey("VantagemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
